In [8]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

data = pd.DataFrame({
    "hours":[1,2,3,4,5],
    "result":[0,0,1,1,1]
})

X = data[["hours"]]
y = data["result"]

print(X)
print(y)

model = LogisticRegression()
model.fit(X,y)

model.predict([[2]])



   hours
0      1
1      2
2      3
3      4
4      5
0    0
1    0
2    1
3    1
4    1
Name: result, dtype: int64


C:\Users\msade\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [26]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

data = pd.DataFrame({
    "hours":  [1,2,3,4,5,6,7,8,9,10],
    "result": [0,0,0,0,1,1,1,1,1,1]  # 0=Fail, 1=Pass
})

#print(data)

X = data[["hours"]]
y = data[["result"]]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

model = LogisticRegression()
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Accuracy : ", accuracy_score(y_test, pred))
print(model.predict([[12]]))













Accuracy :  1.0


C:\Users\msade\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\msade\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

In [40]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix



def make_student_success(n=600, seed=1):

    rng = np.random.default_rng(seed)

    X = pd.DataFrame({
        "hours": rng.integers(0, 12, n),
        "attendance": rng.integers(40, 100, n),
        "sleep": rng.integers(4, 9, n),
        "practice_tests": rng.integers(0, 6, n),
    })

    y = (((X["hours"] >= 5) &
          (X["attendance"] >= 70) &
          (X["sleep"] >= 6))
          |
          (X["practice_tests"] >= 4)).astype(int)

    # Add noise (real-life mistakes)
    y = np.where(rng.random(n) < 0.07, 1-y, y)

    return X, y


#Create the dataset
X, y = make_student_success()

print(X.head())
print(y[:5])

#train and split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

model = LogisticRegression()
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Accuracy : ", accuracy_score(y_test, pred))

new_student = [[12,80,7,2]]
print(model.predict(new_student)[0])






   hours  attendance  sleep  practice_tests
0      5          94      6               5
1      6          56      5               0
2      9          66      8               1
3     11          73      4               3
4      0          69      7               4
[1 0 1 0 1]
Accuracy :  0.8055555555555556
1


C:\Users\msade\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [9]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer


data = pd.DataFrame({
    "text": [
        "Win a free iPhone now",
        "Lowest price deal click here",
        "Hey are we meeting tomorrow?",
        "Can you send the notes?",
        "Free cash prize claim now",
        "Lunch at 1 pm?"
    ],
    "label": [1,1,0,0,1,0]  # 1=spam, 0=not spam
})

X = data["text"]
y = data["label"]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)


#print(X_train)
#print(X_test)

vectorizer = CountVectorizer()
X_train_vec =  vectorizer.fit_transform(X_train)
X_test_vec  =  vectorizer.transform(X_test)

model = LogisticRegression()
model.fit(X_train_vec, y_train)

pred = model.predict(X_test_vec)

msg =["free book for today"]

msg_vec = vectorizer.transform(msg)

print(model.predict(msg_vec)[0])





1
